# Generated by Django 5.2.17 on 2026-10-01 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=120)),
                ('short_name', models.CharField(help_text='Filter chip label', max_length=60)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('director', 'Director'), ('adviser', 'Adviser')], max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=160)),
                ('role', models.CharField(blank=True, max_length=160)),
                ('qualifications', models.CharField(blank=True, max_length=240)),
                ('portfolio', models.CharField(blank=True, max_length=240)),
                ('profile', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='people/')),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['kind', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(help_text="Without 'Brokerage Division'", max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('strapline', models.CharField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True)),
                ('focus_areas', models.JSONField(blank=True, default=list)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desks', to='core.cluster')),
            ],
            options={
                'ordering': ['cluster__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=160)),
                ('contact', models.CharField(help_text='Email or phone', max_length=200)),
                ('message', models.TextField(max_length=4000)),
                ('handled', models.BooleanField(default=False)),
                ('desk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.desk')),
            ],
            options={
                'verbose_name_plural': 'enquiries',
                'ordering': ['-created'],
            },
        ),
    ]
